# Generated by Django 5.1.6 on 2025-04-22 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('insurance_id', models.CharField(max_length=50)),
                ('payer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('npi', models.CharField(max_length=20)),
                ('certification', models.CharField(max_length=100)),
                ('compliance_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('service_code', models.CharField(max_length=20)),
                ('diagnosis_code', models.CharField(max_length=20)),
                ('units', models.IntegerField()),
                ('amount_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_status', models.CharField(default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.provider')),
            ],
        ),
    ]
