# Generated by Django 5.1.6 on 2025-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payer',
            field=models.CharField(max_length=100),
        ),
    ]
