-- Drop the table if it exists
DROP TABLE IF EXISTS rhino_claims;

-- Create the table with all necessary columns
CREATE TABLE rhino_claims (
    trading_partner_id VARCHAR(255),
    rb_claim_id VARCHAR(255),
    edi_file_id VARCHAR(255),
    edi_file_name VARCHAR(255),
    provider_name VARCHAR(255),
    payer_provider_id VARCHAR(255),
    provider_npi VARCHAR(255),
    patient_first_name VARCHAR(255),
    patient_last_name VARCHAR(255),
    patient_payer_id VARCHAR(255),
    original_claim_id VARCHAR(255),
    adjustment_claim_id VARCHAR(255),
    icn VARCHAR(255),
    payer VARCHAR(255),
    payer_type VARCHAR(255),
    procedure_code VARCHAR(255),
    created_date DATE,
    service_begin_date DATE,
    service_end_date DATE,
    total_hours NUMERIC,
    total_units NUMERIC,
    patient_responsibility NUMERIC,
    total_billed NUMERIC,
    total_paid NUMERIC,
    paycheck_date DATE,
    claim_status VARCHAR(255),
    patient_sex VARCHAR(50),
    patient_dob DATE,
    patient_address_1 VARCHAR(255),
    patient_address_2 VARCHAR(255),
    patient_city VARCHAR(255),
    patient_state VARCHAR(50),
    patient_zip VARCHAR(20),
    prior_authorization VARCHAR(255),
    discharge_date DATE,
    diagnosis_1 VARCHAR(255),
    diagnosis_2 VARCHAR(255),
    diagnosis_3 VARCHAR(255),
    diagnosis_4 VARCHAR(255),
    orp_first_name VARCHAR(255),
    orp_last_name VARCHAR(255),
    orp_npi VARCHAR(255),
    accident_type VARCHAR(255)
);
