name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Image
        run: docker build -t backend ./backend

      - name: Install Node and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Render (auto)
        run: echo "Render will auto-deploy from GitHub push to main branch"