# Generated by Django 5.1.6 on 2025-05-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_patient_photo_alter_patient_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RhinoClaim',
            fields=[
                ('trading_partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rb_claim_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('edi_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('edi_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_npi', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('total_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('original_claim_id', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustment_claim_id', models.CharField(blank=True, max_length=255, null=True)),
                ('icn', models.CharField(blank=True, max_length=255, null=True)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('service_begin_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('patient_responsibility', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paycheck_date', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_city', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_state', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('prior_authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('diagnosis_1', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_2', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_3', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_4', models.CharField(blank=True, max_length=255, null=True)),
                ('orp_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('orp_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('orp_npi', models.CharField(blank=True, max_length=255, null=True)),
                ('accident_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audits_rhino_claim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], max_length=20)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingrecord')),
            ],
        ),
    ]
