# Generated by Django 5.1.6 on 2025-05-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='flags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
