# Generated by Django 5.1.6 on 2025-05-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auditissue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
