# Generated by Django 5.1.6 on 2025-05-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('npi', models.CharField(max_length=50)),
                ('compliance_status', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
            ],
        ),
    ]
